ALTER TABLE products
  ADD COLUMN IF NOT EXISTS weight_g integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS length_cm integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS width_cm integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS height_cm integer NOT NULL DEFAULT 1;
